### ISSUE TITLE
Redimensionner logo fournisseurs

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#451]
Tous les logos fournisseurs sont ici : https://github.com/etalab/admin_api_entreprise/tree/develop/app/assets/images/providers

**Comment by skelz0r** [comment]
Il y a < 1Mo de logo au total, le plus gros étant de 156kb (Agefiph): si par "redimensionner" tu entends "trouver des logos en meilleur définition" alors oui, le cas contraire je pense que ça ne sert pas.

Ou alors tu parles du html ?

**Comment by DorineLam** [comment]
Non non, d'ailleurs je risque de ne pas avoir une si bonne définition ! 
Je parle d'un redimensionnement graphique. Pour que les logos horizontaux ne soient plus désavantagés en termes de taille.
Je vais placer tous les logos dans un gabarit identique.

**Comment by skelz0r** [comment]
imo un truc comme ça fonctionne

```html
<div class="logo-wrapper">
  <div class="logo" style="background-url:(<%= image_path(provider.logo) %>);"></div>
</div>
```

```css
.logo-wrapper {
  position: relative;
  width: 200px;
  height: 200px;
}

.logo {
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  left: 100%;
  background-image: cover;
}
```

Après si c'est plus simple go, faudra garder en tête cependant que ces logos seront potentiellement utilisés ailleurs.
