### ISSUE TITLE
Refactoriser la configuration redis (rendre ça débrayable pour la prod)

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#825]
Go load ça depuis un fichier.

Le format `redis.yml`

```yaml
production:
  host: 'localhost'
  port: 6379
  username: siade
  password: supersecretpassword
```

dans `application.rb`

```ruby
  config.redis_params = config_for(:redis)
```

dans l'app là où on va chercher des redis co:

```ruby
Redis.new(Rails.application.redis_params)
```

Penser à modifier mina aussi pour le lien symbolique.

Related https://github.com/etalab/very_ansible/issues/133
